Repository SpellholdStudios/BGT-WeiDU, pull requests merged in 2021-07, with the labels that each got.

#36 Map labels
  bgt/base/map/worldmap.wmp
  bgt/worldmap/czech/worldmap.tra
  bgt/worldmap/english/worldmap.tra
  bgt/worldmap/french/worldmap.tra
  bgt/worldmap/german/worldmap.tra
  bgt/worldmap/italian/worldmap.tra
  bgt/worldmap/korean/worldmap.tra
  bgt/worldmap/polish/worldmap.tra
  bgt/worldmap/russian/worldmap.tra
  bgt/worldmap/schinese/worldmap.tra
  bgt/worldmap/spanish/worldmap.tra
  bgt/worldmap/tchinese/worldmap.tra
Labels: feature

#37 Fix Firebead 300 gp trick
  bgt/base/d_bg1/fireb1.d
  bgt/base/d_bg1/firebe.d
Labels: bug

#38 Make Raiken and Teven leave their areas after bandit camp
  bgt/base/d_bg1/bandcr.d
  bgt/base/d_bg1/bandct.d
Labels: bug

#39 Make Kirinhale recognize speaker's gender
  bgt/base/d_bg1/kirinhal.d
Labels: bug

#40 Fix trap detection in Durlag's Tower, Balduran's ship and Cloakwood Mines
  bgt/bgt.tp2
Labels: bug

#42 Make Zeke see Branwen isn't petrified anymore
  bgt/base/d_bg1/zeke.d
Labels: bug

#43 Fix Dushai dlg
  bgt/base/d_bg1/dushai.d
Labels: bug

#41 New worldmap with artwork by dex909
  bgt/base/map/bpbgtmap.bam
  bgt/base/map/worldmap.wmp
  bgt/base/mos/bpbgtmap.mos
  bgt/bgt.tp2
  bgt/modify/are/ar7900.are
  bgt/modify/are/ar8700.are
  bgt/modify/are/ard000.are
  bgt/worldmap/areas.tbl
Labels: feature, question

#44 BG1UB: Appropriate Albert and Rufie Reward
  bgt/base/d_bg1/albert.d
Labels: feature

#45 BG1UB: Coran and the Wyverns
  bgt/bgt.tp2
  bgt/fixpack/rcoran.d
Labels: bug

#46 BG1UB: Permanent Corpses
  bgt/bgt.tp2
Labels: bug

#47 Make Arkanis and Deder follow only after dialogue
  bgt/bgt.tp2
  bgt/fixpack/rarkani3.d
Labels: feature

#48 Stop NPCs with follow script pushing player
  bgt/bgt.tp2
Labels: feature

#49 Restore Emerson's unused lines
  bgt/bgt.tp2
  bgt/fixpack/remerso.d
Labels: feature

#50 Restore Gerde and Fenten angry states
  bgt/base/d_bg1/fenten.d
  bgt/bgt.tp2
  bgt/fixpack/aar8300.baf
  bgt/fixpack/rfenten.d
  bgt/fixpack/rgerde.d
  bgt/language/czech/setup.tra
  bgt/language/english/setup.tra
  bgt/language/french/setup.tra
  bgt/language/german/setup.tra
  bgt/language/italian/setup.tra
  bgt/language/korean/setup.tra
  bgt/language/polish/setup.tra
  bgt/language/russian/setup.tra
  bgt/language/schinese/setup.tra
  bgt/language/spanish/setup.tra
  bgt/language/tchinese/setup.tra
Labels: feature

#51 Weapon names convention
  bgt/language/polish/setup.tra
Labels: translation

#53 Polish Journal entries - more cleanup
  bgt/language/polish/dialog.tra
  bgt/language/polish/journal.tra
Labels: translation

#55 Add chapter check to Lestor's info about mines
  bgt/bgt.tp2
  bgt/fixpack/alestor.d
Labels: bug
